import SiteShell from "@/components/layouts/SiteShell";
import { cn } from "@/utils/cn";
import localFont from "next/font/local";
import "./globals.css";

const fontBody = localFont({
  src: "../public/fonts/ppneuemontreal-regular.woff2",
  variable: "--font-body",
});

const fontMigra = localFont({
  src: [
    {
      path: "../public/fonts/ppmigra-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/ppmigra-italic.woff2",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-migra",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn("antialiased", fontBody.variable, fontMigra.variable)}
      >
        <SiteShell>{children}</SiteShell>
      </body>
    </html>
  );
}
