import SiteShell from "@/components/layouts/SiteShell";
import { cn } from "@/utils/cn";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: "variable",
  variable: "--font-inter"
});

const typold = localFont({
  src: [
    {
      path: "../public/fonts/typold-thin.woff",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/typold-thin-italic.woff",
      weight: "100",
      style: "italic",
    },
    {
      path: "../public/fonts/typold-extrathin.woff",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/typold-extrathin-italic.woff",
      weight: "200",
      style: "italic",
    },
    {
      path: "../public/fonts/typold-light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/typold-light-italic.woff",
      weight: "300",
      style: "italic",
    },
    {
      path: "../public/fonts/typold-regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/typold-italic.woff",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/typold-medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/typold-medium-italic.woff",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/fonts/typold-bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/typold-bold-italic.woff",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/fonts/typold-extrabold.woff",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/typold-extrabold-italic.woff",
      weight: "800",
      style: "italic",
    },
    {
      path: "../public/fonts/typold-black.woff",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/typold-black-italic.woff",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-typold",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn("antialiased", typold.variable, inter.variable)}
      >
        <SiteShell>{children}</SiteShell>
      </body>
    </html>
  );
}
